# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(['manage.py'],
             pathex=[],
             binaries=[],
             datas=[ ('templates', 'templates'),
                ('static','static'),
                  ('locale','locale'),
                  ('fonts\\SimSun.ttf','.'),
                  ('Draw_Process\\functions.json','.\\Draw_Process\\'),
                  ('Draw_Process\\packages.json','.\\Draw_Process\\'),
                  ('Draw_Process\\SAP_Action.json','.\\Draw_Process\\'),
                  ('Draw_Process\\setting.txt','.\\Draw_Process\\'),
                  ('Client\\ChocLead.exe','.\\Client\\'),
                  ('run-server.bat','.')
                 ],
             hiddenimports=[ 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.core.management',
    'dwebsocket',
    'dwebsocket.backends',
    'dwebsocket.backends.default',
     'dwebsocket.backends.default.factory',
    'Draw_Process','pymysql',
    'django.template.defaulttags',
    ],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='manage',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='manage')
